# 数据源配置
spring:
  flyway:
    enabled: true
    locations: classpath:db/sqlite
    baselineOnMigrate: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.sqlite.JDBC
    druid:
      url: jdbc:sqlite:${SQLITE_PATH:demo.sqlite}
      username:
      password:

